################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:

    samplenetGenesis:
        Orderer:
            # Orderer Type: The orderer implementation to start
            # Available types are "solo" and "kafka"
            OrdererType: kafka

            Addresses: 
                - orderer1.samplenet.com:7050
            
                - orderer2.samplenet.com:7050
            
                - orderer3.samplenet.com:7050
            
            # Batch Timeout: The amount of time to wait before creating a batch
            BatchTimeout: 2s

            # Batch Size: Controls the number of messages batched into a block
            BatchSize:

                # Max Message Count: The maximum number of messages to permit in a batch
                MaxMessageCount: 10

                # Absolute Max Bytes: The absolute maximum number of bytes allowed for
                # the serialized messages in a batch.
                AbsoluteMaxBytes: 99 MB

                # Preferred Max Bytes: The preferred maximum number of bytes allowed for
                # the serialized messages in a batch. A message larger than the preferred
                # max bytes will result in a batch larger than preferred max bytes.
                PreferredMaxBytes: 512 KB

            Kafka:
                # Brokers: A list of Kafka brokers to which the orderer connects
                # NOTE: Use IP:port notation
                Brokers:
                    - kafka1.samplenet.com:9092
                    - kafka2.samplenet.com:9092
                    - kafka3.samplenet.com:9092

            # Organizations is the list of orgs which are defined as participants on
            # the orderer side of the network
            Organizations:
                - *ordererOrg
        Consortiums:
            samplenetConsortium:
                Organizations: 
                    - *org1
    samplenetChannel:
        Consortium: samplenetConsortium
        Application:
            Organizations: 
                - *org1

################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &ordererOrg
        Name: ordererOrg

        # ID to load the MSP definition as
        ID: ordererOrgMSP

        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: volumes/crypto-config/ordererOrganizations/samplenet.com/msp

    
    - &org1
        Name: org1

        # ID to load the MSP definition as
        ID: org1MSP

        MSPDir: volumes/crypto-config/peerOrganizations/org1.samplenet.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            
            - Host: peer1.org1.samplenet.com
              Port: 7051
            
    
