################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:

    {{.Name}}Genesis:
        Orderer:
            # Orderer Type: The orderer implementation to start
            # Available types are "solo" and "kafka"
            OrdererType: {{.OrdererType}}

            Addresses: {{range $.Orderers}}
                - {{.Name}}:{{.Port}}
            {{end}}
            # Batch Timeout: The amount of time to wait before creating a batch
            BatchTimeout: 2s

            # Batch Size: Controls the number of messages batched into a block
            BatchSize:

                # Max Message Count: The maximum number of messages to permit in a batch
                MaxMessageCount: 10

                # Absolute Max Bytes: The absolute maximum number of bytes allowed for
                # the serialized messages in a batch.
                AbsoluteMaxBytes: 99 MB

                # Preferred Max Bytes: The preferred maximum number of bytes allowed for
                # the serialized messages in a batch. A message larger than the preferred
                # max bytes will result in a batch larger than preferred max bytes.
                PreferredMaxBytes: 512 KB

            Kafka:
                # Brokers: A list of Kafka brokers to which the orderer connects
                # NOTE: Use IP:port notation
                Brokers:{{range $.KafkaBrokers}}
                    - {{.Name}}:9092{{end}}

            # Organizations is the list of orgs which are defined as participants on
            # the orderer side of the network
            Organizations:
                - *{{.OrdererOrganization.Name}}
        Consortiums:
            {{.Name}}Consortium:
                Organizations: {{range $.PeerOrganizations}}
                    - *{{.Name}}{{end}}
    {{.Name}}Channel:
        Consortium: {{.Name}}Consortium
        Application:
            Organizations: {{range $.PeerOrganizations}}
                - *{{.Name}}{{end}}

################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &{{$.OrdererOrganization.Name}}
        Name: {{$.OrdererOrganization.Name}}

        # ID to load the MSP definition as
        ID: {{$.OrdererOrganization.Name}}MSP

        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: volumes/crypto-config/ordererOrganizations/{{$.Domain}}/msp

    {{range $.PeerOrganizations}}
    - &{{.Name}}
        Name: {{.Name}}

        # ID to load the MSP definition as
        ID: {{.Name}}MSP

        MSPDir: volumes/crypto-config/peerOrganizations/{{.FullName}}/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            {{$orgName := .Name}}{{range $.Peers}}{{if eq .Organization.Name $orgName}}
            - Host: {{.Name}}
              Port: {{.Port}}
            {{end}}{{end}}
    {{end}}
